apiVersion: apps/v1
kind: Deployment
metadata:
  name: availability-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: availability-api
  template:
    metadata:
      labels:
        app: availability-api
    spec:
      containers:
        - name: availability-api
          image: nelsonsozinho/availability.api:latest
          env:
            - name: DB_USER
              value: postgres
            - name: DB_PASSWORD
              value: postgres
            - name: DB_DATABASE
              value: availability
            - name: DB_DATABASE_HOST
              value: postgres
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: availability-api
spec:
  selector:
    app: availability-api
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer