apiVersion: apps/v1
kind: Deployment
metadata:
  name: loan-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loan-api
  template:
    metadata:
      labels:
        app: loan-api
    spec:
      containers:
        - name: loan-api
          image: nelsonsozinho/loan.api:latest
          env:
            - name: DB_USERNAME
              value: postgres
            - name: DB_PASSWORD
              value: postgres
            - name: DB_DATABASE_HOST
              value: postgres
            - name: DB_DATABASE
              value: loan
            - name: BOOTSTRAP_SERVER
              value: kafka
            - name: BOOTSTRAP_PORT
              value: "29092"
            - name: AVAILABILITY_API
              value: http://availability-api:8080/restriction
            - name: SCORE_API
              value: http://score-api:8080/score
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: loan-api
spec:
  selector:
    app: loan-api
  ports:
    - port: 8080
      targetPort: 8080