apiVersion: apps/v1
kind: Deployment
metadata:
  name: bank-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bank-api
  template:
    metadata:
      labels:
        app: bank-api
    spec:
      containers:
        - name: bank-api
          image: nelsonsozinho/bank.api:latest
          env:
            - name: SPRING_DATASOURCE_USERNAME
              value: postgres
            - name: SPRING_DATASOURCE_PASSWORD
              value: postgres
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://postgres:5432/bank
            - name: BOOTSTRAP_SERVER
              value: kafka
            - name: BOOTSTRAP_PORT
              value: "29092"
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: bank-api
spec:
  selector:
    app: bank-api
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30282
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: availability-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: availability-api
  template:
    metadata:
      labels:
        app: availability-api
    spec:
      containers:
        - name: availability-api
          image: nelsonsozinho/availability.api:latest
          env:
            - name: SPRING_DATASOURCE_USERNAME
              value: postgres
            - name: SPRING_DATASOURCE_PASSWORD
              value: postgres
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://postgres:5432/availability
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: availability-api
spec:
  selector:
    app: availability-api
  ports:
    - port: 8080
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: loan-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loan-api
  template:
    metadata:
      labels:
        app: loan-api
    spec:
      containers:
        - name: loan-api
          image: nelsonsozinho/loan.api:latest
          env:
            - name: SPRING_DATASOURCE_USERNAME
              value: postgres
            - name: SPRING_DATASOURCE_PASSWORD
              value: postgres
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://postgres:5432/loan
            - name: BOOTSTRAP_SERVER
              value: kafka
            - name: BOOTSTRAP_PORT
              value: "29092"
            - name: AVAILABILITY_API
              value: http://availability-api:8080/restriction
            - name: SCORE_API
              value: http://score-api:8080/score
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: loan-api
spec:
  selector:
    app: loan-api
  ports:
    - port: 8080
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: score-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: score-api
  template:
    metadata:
      labels:
        app: score-api
    spec:
      containers:
        - name: score-api
          image: nelsonsozinho/score.api:latest
          env:
            - name: SPRING_DATASOURCE_USERNAME
              value: postgres
            - name: SPRING_DATASOURCE_PASSWORD
              value: postgres
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://postgres:5432/score
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: score-api
spec:
  selector:
    app: score-api
  ports:
    - port: 8080
      targetPort: 8080
